project:
  type: website

website:
  title: "Serviços"
  navbar:
    left:
      - href: index.qmd
        text: Excel

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

